### PR TITLE
Reload payment methods vc when a new method is added

### LINKED ISSUE #584: Reload the payment list view controller when a new method is added
To make it easier to diagnose your issue, please fill out the following:

## Summary

Currently, the payment list view controller is not reloaded when a new payment method is added.

## Code to reproduce

```swift
extension SettingsCoordinator: STPPaymentMethodsViewControllerDelegate {
    func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didSelect paymentMethod: STPPaymentMethod) {
        // Do nothing
    }
    
    func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didFailToLoadWithError error: Error) {
        paymentMethodsViewController.hideViewController()
        
        AlertPresenter.errorPresenter(message: NSLocalizedString("Unable to load payment options", comment: ""))
            .present()
    }
    
    func paymentMethodsViewControllerDidFinish(_ paymentMethodsViewController: STPPaymentMethodsViewController){
        /*
         This will pop both the list controller and “add card” controller, necessary when a new card is added because 
         the underlying list doesn’t reload on its own.
         */
        paymentMethodsViewController.dismiss(completion: nil)
    }
}
```

## iOS version

9-10

## Installation method

CocoaPods

## SDK version

10

### PR DESCRIPTION
**Pull request by bg-stripe**
r? @bdorfman-stripe 

Fixes #584

### CODE REVIEW

File: Stripe/STPPaymentMethodsInternalViewController.m [hunk 1]
```diff
@@ -145,6 +145,16 @@ - (CGFloat)tableView:(__unused UITableView *)tableView heightForHeaderInSection:
     return 0.01f;
 }
 
+- (void)updateWithPaymentMethodTuple:(STPPaymentMethodTuple *)tuple {
+    if (self.paymentMethods == tuple.paymentMethods && self.selectedPaymentMethod == tuple.selectedPaymentMethod) {
```
Comment (bdorfman-stripe) [inline Stripe/STPPaymentMethodsInternalViewController.m]: Should this be `isEqual` or are you intentionally checking for pointer comparison?

Comment (bg-stripe) [inline Stripe/STPPaymentMethodsInternalViewController.m]: ah whoops, good catch – i'll fix
