### PR TITLE
Fix country field bug in shipping form

### LINKED ISSUE #509: Country Picker Doesn't Update on First Selection
## Summary
This should be a relatively simple fix; however, on first selection the country code picker doesn't update. For example, when I click on the picker the option United States shows up but I actually have to scroll to Afghanistan and then scroll back up to United States for the value to update.

## Code to reproduce
Any project using Stripe's STPShippingAddressViewController has this issue. Just present the View Controller and try changing the country. When you select it the value isn't updated. You have to scroll it to Afghanistan and back to the United States in order to select the US.

## iOS version
iOS 10.1.1 (14B100)

## Installation method
Cocoapods

## SDK version
9.2.0

### PR DESCRIPTION
**Pull request by bg-stripe**
r? @bdorfman-stripe 

Fixes #509 

This bug occurs when `STPShippingAddressVC` is passed `prefilledInformation`:
  - We were creating a new address with a `nil` country
  - The address setter wasn't calling `delegateCountryCodeDidChange`

## Testing

I've added a regression assert to `STPAddressViewModelTest`

### CODE REVIEW

File: Stripe/STPAddressViewModel.m [hunk 1]
```diff
@@ -224,6 +224,7 @@ - (void)setAddress:(STPAddress *)address {
                 break;
             case STPAddressFieldTypeCountry:
                 cell.contents = address.country;
+                [cell delegateCountryCodeDidChange:address.country];
```
Comment (bdorfman-stripe) [inline Stripe/STPAddressViewModel.m]: This should be called above on line 203? Is that not working properly somehow?

Comment (bg-stripe) [inline Stripe/STPAddressViewModel.m]: ah yup, good point, I was a bit too quick to jump to this as a fix. Turns out the issue was actually in `setContents` – previously, we were setting the country field's text to the country code, instead of getting the name from the country picker.

File: Stripe/STPShippingAddressViewController.m [hunk 2]
```diff
@@ -75,6 +75,7 @@ - (instancetype)initWithConfiguration:(STPPaymentConfiguration *)configuration
         }
         else if (prefilledInformation != nil) {
             STPAddress *prefilledAddress = [STPAddress new];
+            prefilledAddress.country = _addressViewModel.address.country;
```
Comment (bdorfman-stripe) [inline Stripe/STPShippingAddressViewController.m]: Is this bug limited to the shipping screen or should we make the same fix for billing also?

**Comment by bdorfman-stripe** [comment]
LGTM
